kind: pipeline
type: docker
name: awsbuilders-poweron

clone:
  disable: true

steps:
- name: start-aws-instances
  pull: always
  image: amazon/aws-cli
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
    - aws ec2 start-instances --region eu-north-1 --instance-ids i-01e3d598710a23947 i-02bb3cbe63a2b3fef

trigger:
  branch:
    include:
    - master
    - main
  event:
    include:
    - push
    - pull_request
    - tag

---
kind: pipeline
name: build-image-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: odysseyondocker-gcc11-amd64
  image: plugins/docker
  settings:
    repo: walkero/odysseyondocker
    tags:
      - latest-gcc11-amd64
    cache_from:
      - walkero/odysseyondocker:latest-gcc11-amd64
    purge: true
    compress: true
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push

depends_on:
  - awsbuilders-poweron

node:
  agents: awsbuilders

---
kind: pipeline
name: build-image-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: odysseyondocker-gcc11-arm64
  image: plugins/docker
  settings:
    repo: walkero/odysseyondocker
    tags:
      - latest-gcc11-arm64
    cache_from:
      - walkero/odysseyondocker:latest-gcc11-arm64
    purge: true
    compress: true
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push

depends_on:
  - awsbuilders-poweron

node:
  agents: awsbuilders

---
kind: pipeline
name: build-manifest-odysseyondocker-gcc11

steps:
- name: manifest-odysseyondocker-gcc11
  image: plugins/manifest
  settings:
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
    target: walkero/odysseyondocker:latest-gcc11
    template: walkero/odysseyondocker:latest-gcc11-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

depends_on:
  - build-image-amd64
  - build-image-arm64

trigger:
  branch:
    include:
    - master
    - main
  event:
    include:
    - push